name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version:
          - 1.8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java-version }}

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: detekt

      - name: Build with Gradle
        run: ./gradlew build
