name: Client CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 1.8

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ktlintCheck detekt

      - name: Build with Gradle
        run: ./gradlew build
